### PR TITLE
Clean CPU examples

### PR DESCRIPTION
**Pull request by Daval-G**
This PR cleans the CPU examples in several ways:
- Change brain orientations to the medical standard
- Reduce blank spaces around images
- Remove some overlaps in figures
- Split script-specific code from the utils and data preparation
- Homogeneize parts and subparts names & structures
- Homogeneize one-line descriptions
- Homogeneize capitalizations, punctuations
- Apply isort to clean imports
- Fix a bunch of typos
- Fix paragraph irregularities
- Fix a few cross references
- Break lines sometimes
- Remove a few dead parts
- Remove many useless outputs
- Remove references to MFI in off-resonance operator (we don't do MFI but the opposite)

I will try to do the same for GPU examples later. Note that trajectory examples are barely touched, not because they are perfect but the opposite as I plan to break them into smaller examples as discussed in #118.

### CODE REVIEW

**Review by paquiteau — APPROVED** [review]
Very nice improvements, thanks! 

If you wish, you can also tackle #182 in this as well.

**Comment by paquiteau** [comment]
> By the way, how can we change the examples order in the gallery ? It doesn't make sense

RTFM :upside_down_face:  https://sphinx-gallery.github.io/stable/configuration.html#within-gallery-order

there are multiple possibilities; I guess `FileNameSortKey` and a proper naming scheme (`example_01_...`) could do the trick.

**Comment by Daval-G** [comment]
> Very nice improvements, thanks!
> 
> If you wish, you can also tackle #182 in this as well.

Done

**Comment by Daval-G** [comment]
> > By the way, how can we change the examples order in the gallery ? It doesn't make sense
> 
> RTFM 🙃 https://sphinx-gallery.github.io/stable/configuration.html#within-gallery-order
> 
> there are multiple possibilities; I guess `FileNameSortKey` and a proper naming scheme (`example_01_...`) could do the trick.

For now let's sort by example name rather than filename, until we decide of a specific order

**Comment by Daval-G** [comment]
@paquiteau I cleaned the new CG example who seem to be problematic even on the main branch, but even after fix it doesn't work as intended on my side (image not showing because the algorithm doesn't converge). I moved it to GPU examples because it uses gpuNUFFT even though I doubt it is a requirement, but since it didn't work on my side I didn't want to change too many things

**Review by paquiteau — APPROVED** [review]
LGTM ! Thanks again :)

**Pull request merged**
