### PR TITLE
Add TURBINE/REPI with EPI-based tools

### PR DESCRIPTION
**Pull request by Daval-G**
This PR adds the following features:
- `initialize_3D_TURBINE` function to create a TURBINE trajectory requested in issues #50, that consists in EPI shots rotated into a cylinder,
- `initialize_3D_REPI` function to create a REPI trajectory requested in issues #49, that can be either radial or spiral EPI-like shots interlaced between blades rather than stacked independently
- `epify` function used to combine shots into a single multi-echo readout train, similar to EPI shots
- `prewind` and `rewind` to create the positioning & spoiling gradients before and after the readouts, and therefore obtain the full gradient sequence rather than just the one played during the readouts.

The different functions & features are illustrated below, with the TURBINE & REPI trajectories (up) and the epify/prewind/rewind tools applied to different trajectories (down)

Screenshot from 2024-06-23 18-15-06

Screenshot from 2024-06-23 18-15-36

### CODE REVIEW

**Comment by paquiteau** [comment]
This looks very promising ! I will let you add documentation before reviewing. 

Some thoughts/Questions: 

- Maybe a un-epify method could be added as well if it make sense ? (you have an EPI trajectory with the gradients turns, and you want to only preserve the straight lines for the reconstruction ) 
- Does the original REPI / TURBINE support GRAPPA acceleration ? do we want to add this to MRI-NUFFT ?

**Comment by Daval-G** [comment]
> This looks very promising ! I will let you add documentation before reviewing.
> 
> Some thoughts/Questions:
> 
> * Maybe a un-epify method could be added as well if it make sense ? (you have an EPI trajectory with the gradients turns, and you want to only preserve the straight lines for the reconstruction )

Yes that make sense, I will add that too

> * Does the original REPI / TURBINE support GRAPPA acceleration ? do we want to add this to MRI-NUFFT ?

Didn't read about it, but it is quite certain they can. I would suggest to have it made through another function/tool rather than keep stacking arguments on REPI/TURBINE functions, and add an example where we make them GRAPPA-compatible. It requires to add an option to not epify automatically the REPI & TURBINE functions, but I was planning to propose that anyway.

**Comment by chaithyagr** [comment]
@Daval-G thank you for this work. I was curious if you had something more to be done here? If not, I can handle the linting issue.

**Comment by Daval-G** [comment]
> @Daval-G thank you for this work. I was curious if you had something more to be done here? If not, I can handle the linting issue.

The examples are still missing, that's what I am currently working on

**Comment by Daval-G** [comment]
@paquiteau good to go ?

**Comment by Daval-G** [comment]
There is still the question of the in-plane acceleration, but I plan to do that in another PR

**Review by paquiteau — APPROVED** [review]

**Pull request merged**
