### PR TITLE
A major bug in NSP read trajectory implementation

### PR DESCRIPTION
**Pull request by chaithyagr**
This bug has wide implications. Bascially when OSF>1 (which is usually the case), for the first 0, 1, ... OSF points for each shot, we end up with bad k-space trajectory location which is wrong!

### CODE REVIEW

**Comment by chaithyagr** [comment]
Noting here that the issue mostly affects center-out trajectories adversly

**Comment by paquiteau** [comment]
good catch ! you might want to lint your code however ;)

**Comment by chaithyagr** [comment]
I just thought i did xD didnt commit damn it.

**Comment by chaithyagr** [comment]
This is bizzare, I thought this was merged! @paquiteau any idea how we missed this, can I merge it?

**Pull request merged**
