### PR TITLE
fix: Off-resonance array backend checks.

### LINKED ISSUE #203: Distortion correction with a known fieldmap using mri-nufft
Hello

I am wondering if I can discuss a problem I encounter right now by going through what I have and what I did with you. I would like to see if there are step I done incorrectly.

I have SE-EPI kspace data where N/2 ghosting correction and regriding has been performed and reverse readout lines are time reversed. So my kspace is currently a uniformed sampled 64x64 Cartesian grid for each slice. So now the phase error caused by inhomogeneity is the only thing that making the kspace non-uniformed. 

Since I have acquired both PE directions so I used TOPUP and generate a fieldmap (unit: Hz) to use in this reconstruction.  I had to generate the k-trajectory and sample time array on my own because there isn't a choice for cartesian. I generate k_trajectory that start from [-kmax, -kmax] and end at [kmax, kmax]. So basically from bottom line to top line. Am I doing this k-trajectory correctly?

I then generate the nufft operator using finufft and the off-resonace correction nufft operator using the nufft operator, the fieldmap and sample time matrix. Since I have the kspace data, I perform the adjoin_op using the off-resonance correct nufft operator. I perform the correction on each channel's data and combined them using root of sum of square (same as the scanner). It is fine to directly use adjoint_op on k-space correct? I don't need to first perform orc_nufft.op to distorted image data to get kspace. 

The correction looks good on some of the slice where there isn't a large field at the temporal region.
image
It can be seen that the distortion correction is done according to the field effect. 

However, the correct looks quite strange for those slice where a large field presented at the temporal. 
image

Since it does feel like that the correction is done according to the induced phase effect from the fieldmap. Would you think the fieldmap from TOPUP is not a suitable choice? What are the rule for making the k-trajectory and the sample time array. Since those are the two thing I generate myself so there could be a chance I made mistakes. Or maybe for a more complete image reconstruction, I should formulate my problem in the inverse problem manner to solve it instead of just relying on the nufft operator

Sorry for the long paragraphs and multiple questions. I just started my graduate research on MRI and image processing and am excited to learn from anybody. Please let me know if there are clarification needed for anything above. 

Best
Wenshang

### PR DESCRIPTION
**Pull request by paquiteau**
fixes #203.

### CODE REVIEW

**Review by chaithyagr — APPROVED** [review]
LGTM

**Comment by wenshangwang** [comment]
Hi all
Your edition solve the "Unsupported backend".  There is another bug that happened in the following adj_op section line 314: coeffs_d = self.xp.array(coeffes). Torch does not have the attribute .array(). I implemented a quick fix as:
image
image
This makes it work with torch on my side. Please let me know what you guys eventually change it into. 

Wenshang

**Comment by paquiteau** [comment]
I think just using `asarray` is enough (see the above commit) let me know if you have any other trouble :)

**Comment by wenshangwang** [comment]
I am setting up the mri-nufft operator such that it is operable with torch's autograd. Here is what I did:
`nufft = get_operator("finufft", wrt_data=True)(
    samples=2 * np.pi * k_traj,  # normalize for finufft
    shape=slice_for_shape,
    squeeze_dims = False
)
orc_nufft = off_resonance.MRIFourierCorrected(
    nufft, b0_map=fmap_current, readout_time=t_ro, n_time_segments=10, backend="torch"
)
`
I had to change part of the autodiff.py code into: 
`class _NUFFT_OP(torch.autograd.Function):
    """
    Autograd support for op nufft function.

    This class is implemented by an efficient approximation of Jacobian Matrices.

    References
    ----------
    Wang G, Fessler J A. "Efficient approximation of Jacobian matrices involving a
    non-uniform fast Fourier transform (NUFFT)."
    IEEE Transactions on Computational Imaging, 2023, 9: 43-54.
    """

    @staticmethod
    def forward(x, traj, nufft_op):
        """Forward image -> k-space."""
        #ctx.save_for_backward(x)
        #ctx.nufft_op = nufft_op
        print("Reach forward")
        return nufft_op.op(x)
    
    @staticmethod
    def setup_context(ctx, inputs, output):
        """Save context for the backward pass."""
        x, traj, nufft_op = inputs
        ctx.save_for_backward(x)
        ctx.nufft_op = nufft_op  # Store non-tensor object on ctx
        print("Reach setup")

    @staticmethod
    def backward(ctx, dy):
        """Backward image -> k-space."""
        print("Reach backward")
        x = ctx.saved_tensors[0]
        grad_data = None
        grad_traj = None
        if ctx.nufft_op._grad_wrt_data:
            grad_data = ctx.nufft_op.adj_op(dy)
        if ctx.nufft_op._grad_wrt_traj:
            im_size = x.size()[1:]
            factor = 1
            if ctx.nufft_op.backend in ["gpunufft"]:
                factor *= np.pi * 2
            r = [
                torch.linspace(-size / 2, size / 2 - 1, size) * factor
                for size in im_size
            ]
            grid_r = torch.meshgrid(*r, indexing="ij")
            grid_r = torch.stack(grid_r, dim=0).type_as(x)[:, None]
            grid_x = x * grid_r  # Element-wise multiplication: x * r

            nufft_dx_dom = torch.cat(
                [ctx.nufft_op.op(grid_x[i, ...]) for i in range(grid_x.size(0))],
                dim=0,
            )
            grad_traj = -1j * torch.conj(dy) * nufft_dx_dom
            grad_traj = torch.transpose(
                torch.sum(grad_traj, dim=1),
                0,
                1,
            ).to(NP2TORCH[ctx.nufft_op.dtype])
        return grad_data, grad_traj, None`
     
With the set_context() method added and ctx object taken out of forward method. Kept the code as it was will give 
RuntimeError: In order to use an autograd.Function with functorch transforms (vmap, grad, jvp, jacrev, ...), it must override the setup_context staticmethod. For more details, please see https://pytorch.org/docs/master/notes/extending.func.html"

While this makes the off-resonance compensated nufft operator run with torch.autograd on the orc_nufft without error. But the print out statement shown backward is never reached. The image x stayed at the initial guess. I used a quite standard torch optimization structure which is shown below: 
`import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F

# Assuming your NUFFT operator is defined as follows:
# - Forward operator: nufft_forward(x) -> y (k-space data)
# - Adjoint operator: nufft_adjoint(y) -> x (image data)
# Both functions accept and return PyTorch tensors.

# Replace these placeholder functions with your actual NUFFT implementations.
def nufft_forward(x):
    """
    Forward NUFFT operator.
    x: torch.Tensor of shape (H, W) or (batch_size, H, W)
    Returns y: torch.Tensor of k-space data.
    """
    # Your NUFFT forward implementation here.
    y = orc_nufft.op(x)
    return y

def nufft_adjoint(y):
    """
    Adjoint NUFFT operator.
    y: torch.Tensor of k-space data.
    Returns x: torch.Tensor of image data.
    """
    # Your NUFFT adjoint implementation here.
    x = orc_nufft.adj_op(y)  # Replace with your actual code.
    return x

def reconstruct_image(kspace_data, num_iterations=100, learning_rate=1e-3, regularization_weight=0.01):
    """
    Reconstructs an image from k-space data using NUFFT and PyTorch autograd.

    Args:
        kspace_data (torch.Tensor): Measured k-space data of shape (H, W), complex tensor.
        num_iterations (int): Number of iterations for the optimizer.
        learning_rate (float): Learning rate for the optimizer.
        regularization_weight (float): Weight for the regularization term.

    Returns:
        torch.Tensor: Reconstructed image.
    """

    # Initialize the image with the adjoint of k-space data
    x_init = torch.zeros(64,64, requires_grad=True)
    kspace_data.requires_grad_(True)
    x = x_init

    # Define the optimizer
    optimizer = optim.Adam([x], lr=learning_rate)

    # Reconstruction loop
    for iter in range(num_iterations):
        optimizer.zero_grad()

        # Forward pass: compute the predicted k-space data
        print(x.requires_grad)
        y_pred = nufft_forward(x)
        y_pred.requires_grad_(True)
        x.requires_grad_(True)
        print(x.requires_grad)

        # Data fidelity term: L2 norm between predicted and measured k-space data
        data_fidelity = torch.norm(y_pred - kspace_data) ** 2

        # Regularization term: Total Variation (TV) regularization
        tv_reg = F.l1_loss(x[1:, :], x[:-1, :]) + F.l1_loss(x[:, 1:], x[:, :-1])

        # Total loss
        loss = data_fidelity + regularization_weight * tv_reg
        print(f'"loss grad: {loss.requires_grad}')

        # Backward pass
        loss.backward()

        # Update the image
        print(x.requires_grad)
        optimizer.step()

        # Optionally, print the loss
        if (iter + 1) % 10 == 0:
            print(f"Iteration {iter + 1}/{num_iterations}, Loss: {loss.item():.4f}")

    # Return the reconstructed image
    reconstructed_image = x.detach()
    return reconstructed_image

# Main script
if __name__ == "__main__":
    # Load your k-space data as a torch.Tensor
    # Replace this section with your actual data loading code
    # For example:
    # kspace_data = torch.load('kspace_data.pt')

    kspace_data = torch.from_numpy(kspace)

    # Reconstruct the image
    reconstructed_image = reconstruct_image(
        kspace_data,
        num_iterations=1000,
        learning_rate=0.01,
        regularization_weight=0.01
    )`
 
I am not sure if this comes from my wrongful usage or generation of the operator. BTW, is there test being done with the iterative reconstruction using the off-resonance NUFFT from MRI-NUFFT? I also fed the operator into some other solver such as the one in torchopt. Similar result is produced where the result image is the same with the initial guess. 

Very sorry for this being this long of a message. It is quite late at where I am and my communication ability has dropped significantly. If the operator can work well with the torch based method, half of my problem could be solved, and I feel like we are getting close. 

Wenshang

**Comment by wenshangwang** [comment]
I am setting up the mri-nufft operator such that it is operable with torch's autograd. Here is what I did:
`nufft = get_operator("finufft", wrt_data=True)( samples=2 * np.pi * k_traj, shape=slice_for_shape, squeeze_dims = False ) `

`orc_nufft = off_resonance.MRIFourierCorrected( nufft, b0_map=fmap_current, readout_time=t_ro, n_time_segments=10, backend="torch" ) `

I had to change part of the autodiff.py code into:
`class _NUFFT_OP(torch.autograd.Function):
@staticmethod
def forward(x, traj, nufft_op):
    """Forward image -> k-space."""
    #ctx.save_for_backward(x)
    #ctx.nufft_op = nufft_op
    print("Reach forward")
    return nufft_op.op(x)

@staticmethod
def setup_context(ctx, inputs, output):
    """Save context for the backward pass."""
    x, traj, nufft_op = inputs
    ctx.save_for_backward(x)
    ctx.nufft_op = nufft_op  # Store non-tensor object on ctx
    print("Reach setup")

@staticmethod
def backward(ctx, dy):
    """Backward image -> k-space."""
    print("Reach backward")
    x = ctx.saved_tensors[0]
    grad_data = None
    grad_traj = None
    if ctx.nufft_op._grad_wrt_data:
        grad_data = ctx.nufft_op.adj_op(dy)
    if ctx.nufft_op._grad_wrt_traj:
        im_size = x.size()[1:]
        factor = 1
        if ctx.nufft_op.backend in ["gpunufft"]:
            factor *= np.pi * 2
        r = [
            torch.linspace(-size / 2, size / 2 - 1, size) * factor
            for size in im_size
        ]
        grid_r = torch.meshgrid(*r, indexing="ij")
        grid_r = torch.stack(grid_r, dim=0).type_as(x)[:, None]
        grid_x = x * grid_r  # Element-wise multiplication: x * r

        nufft_dx_dom = torch.cat(
            [ctx.nufft_op.op(grid_x[i, ...]) for i in range(grid_x.size(0))],
            dim=0,
        )
        grad_traj = -1j * torch.conj(dy) * nufft_dx_dom
        grad_traj = torch.transpose(
            torch.sum(grad_traj, dim=1),
            0,
            1,
        ).to(NP2TORCH[ctx.nufft_op.dtype])
    return grad_data, grad_traj, None`
With the set_context() method added and ctx object taken out of forward method. Kept the code as it was will give
RuntimeError: In order to use an autograd.Function with functorch transforms (vmap, grad, jvp, jacrev, ...), it must override the setup_context staticmethod. For more details, please see https://pytorch.org/docs/master/notes/extending.func.html"

While this makes the off-resonance compensated nufft operator run with torch.autograd on the orc_nufft without error. But the print out statement shown backward is never reached. The image x stayed at the initial guess. I used a quite standard torch optimization structure which is shown below:
`import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F

def nufft_forward(x)
y = orc_nufft.op(x)
return y

def nufft_adjoint(y):
x = orc_nufft.adj_op(y) 
return x

def reconstruct_image(kspace_data, num_iterations=100, learning_rate=1e-3, regularization_weight=0.01):

# Initialize the image with the adjoint of k-space data
x_init = torch.zeros(64,64, requires_grad=True)
kspace_data.requires_grad_(True)
x = x_init

# Define the optimizer
optimizer = optim.Adam([x], lr=learning_rate)

# Reconstruction loop
for iter in range(num_iterations):
    optimizer.zero_grad()

    # Forward pass: compute the predicted k-space data
    print(x.requires_grad)
    y_pred = nufft_forward(x)
    y_pred.requires_grad_(True)
    x.requires_grad_(True)
    print(x.requires_grad)

    # Data fidelity term: L2 norm between predicted and measured k-space data
    data_fidelity = torch.norm(y_pred - kspace_data) ** 2

    # Regularization term: Total Variation (TV) regularization
    tv_reg = F.l1_loss(x[1:, :], x[:-1, :]) + F.l1_loss(x[:, 1:], x[:, :-1])

    # Total loss
    loss = data_fidelity + regularization_weight * tv_reg
    print(f'"loss grad: {loss.requires_grad}')

    # Backward pass
    loss.backward()

    # Update the image
    print(x.requires_grad)
    optimizer.step()

    # Optionally, print the loss
    if (iter + 1) % 10 == 0:
        print(f"Iteration {iter + 1}/{num_iterations}, Loss: {loss.item():.4f}")

# Return the reconstructed image
reconstructed_image = x.detach()
return reconstructed_image

if name == "main":
kspace_data = torch.from_numpy(kspace)

# Reconstruct the image
reconstructed_image = reconstruct_image(
    kspace_data,
    num_iterations=1000,
    learning_rate=0.01,
    regularization_weight=0.01
)`
I am not sure if this comes from my wrongful usage or generation of the operator or I probably had not understand the reconstruction problem well enough. BTW, is there test or example being done with the iterative reconstruction using the off-resonance NUFFT from MRI-NUFFT? I would love to learn more on it. I fed the reconstruction inverse problem with our operator into some other solver such as the solve_norm_cg in torchopt. Similar result is produced where the result image is the same with the initial guess and the backward is never reached. 

Very sorry for this being this long of a message. It is quite late at where I am and my communication ability has dropped significantly. If the operator can work well with the torch based method, half of my problem could be solved, and I feel like we are getting close.

Wenshang

**Comment by wenshangwang** [comment]
I am setting up the mri-nufft operator such that it is operable with torch's autograd. Here is what I did:
`nufft = get_operator("finufft", wrt_data=True)( samples=2 * np.pi * k_traj, shape=slice_for_shape, squeeze_dims = False )`

`orc_nufft = off_resonance.MRIFourierCorrected( nufft, b0_map=fmap_current, readout_time=t_ro, n_time_segments=10, backend="torch" )`

I had to change part of the autodiff.py code into:
image

With the set_context() method added and ctx object taken out of forward method. Kept the code as it was will give
RuntimeError: In order to use an autograd.Function with functorch transforms (vmap, grad, jvp, jacrev, ...), it must override the setup_context staticmethod. For more details, please see https://pytorch.org/docs/master/notes/extending.func.html"

While this makes the off-resonance compensated nufft operator run with torch.autograd on the orc_nufft without error. But the print out statement shown backward is never reached. The image x stayed at the initial guess. I used a quite standard torch optimization structure which is shown below:
  `import torch
  import torch.nn as nn
  import torch.optim as optim
  import torch.nn.functional as F
  
  def nufft_forward(x):
  y = orc_nufft.op(x)
  return y
  
  def nufft_adjoint(y):
  x = orc_nufft.adj_op(y)
  return x
  
  def reconstruct_image(kspace_data, num_iterations=100, learning_rate=1e-3, regularization_weight=0.01):
  
  x_init = torch.zeros(64,64, requires_grad=True)
  kspace_data.requires_grad_(True)
  x = x_init
  
  # Define the optimizer
  optimizer = optim.Adam([x], lr=learning_rate)
  
  # Reconstruction loop
  for iter in range(num_iterations):
      optimizer.zero_grad()
  
      # Forward pass: compute the predicted k-space data
      print(x.requires_grad)
      y_pred = nufft_forward(x)
      y_pred.requires_grad_(True)
      x.requires_grad_(True)
      print(x.requires_grad)
  
      # Data fidelity term: L2 norm between predicted and measured k-space data
      data_fidelity = torch.norm(y_pred - kspace_data) ** 2
  
      # Regularization term: Total Variation (TV) regularization
      tv_reg = F.l1_loss(x[1:, :], x[:-1, :]) + F.l1_loss(x[:, 1:], x[:, :-1])
  
      # Total loss
      loss = data_fidelity + regularization_weight * tv_reg
      print(f'"loss grad: {loss.requires_grad}')
  
      # Backward pass
      loss.backward()
  
      # Update the image
      print(x.requires_grad)
      optimizer.step()
  
      # Optionally, print the loss
      if (iter + 1) % 10 == 0:
          print(f"Iteration {iter + 1}/{num_iterations}, Loss: {loss.item():.4f}")
  
  
  reconstructed_image = x.detach()
  return reconstructed_image
  if name == "main":
  kspace_data = torch.from_numpy(kspace)
  
  reconstructed_image = reconstruct_image(
      kspace_data,
      num_iterations=1000,
      learning_rate=0.01,
      regularization_weight=0.01
  )`
I am not sure if this comes from my wrongful usage or generation of the operator or I probably had not understand the reconstruction problem well enough. BTW, is there test or example being done with the iterative reconstruction using the off-resonance NUFFT from MRI-NUFFT? I would love to learn more on it. I fed the reconstruction inverse problem with our operator into some other solver such as the solve_norm_cg in torchopt. Similar result is produced where the result image is the same with the initial guess and the backward is never reached.

Very sorry for this being this long of a message. It is quite late at where I am and my communication ability has dropped significantly. If the operator can work well with the torch based method, half of my problem could be solved, and I feel like we are getting close.

Wenshang

**Comment by chaithyagr** [comment]
Do you want to cover adding example in this PR, or can we merge this?

**Comment by chaithyagr** [comment]
Also @wenshangwang if you are interested, feel free let us know if you want to make a short example. We can help you along if required.

**Comment by paquiteau** [comment]
we can merge I think, and write an example later (ie in a new PR)

**Pull request merged**
