### PR TITLE
Fix violation check rule

### PR DESCRIPTION
**Pull request by chaithyagr**

### CODE REVIEW

**Comment by paquiteau** [comment]
Why don't you just negate the array in your code ? :D

**Comment by chaithyagr** [comment]
Ahhh you want to have bugs to fix bugs, nice xD 
Shall i change this line 

https://github.com/mind-inria/mri-nufft/blob/57765d5143f549df8ee8d64ab621df56d1b98a8b/src/mrinufft/io/nsp.py#L237-L242


to `if not violation:`, then warn? :P

**Comment by paquiteau** [comment]
or `s/violation/valid/` and then `if not all(valid):` ?

**Comment by chaithyagr** [comment]
Just approve and merge bro xD

**Comment by chaithyagr** [comment]
Lol I didn't think this PR will have su much discussion xD I thought it would be, oops missed that

**Comment by Daval-G** [comment]
I tend to agree with @paquiteau, why change this function when it is just misused ? We can surely discuss whether those functions should check validity or violation, but for now the only bug is in [mri-nufft/src/mrinufft/io/nsp.py](https://github.com/mind-inria/mri-nufft/blob/57765d5143f549df8ee8d64ab621df56d1b98a8b/src/mrinufft/io/nsp.py#L237-L242)

**Comment by chaithyagr** [comment]
I give up xD

**Pull request merged**
