### PR TITLE
Change density to density_compensators

### PR DESCRIPTION
**Pull request by Lenoush**
change : tfmri.estimate_density( samples, shape, method="pipe", max_iter=15)
to : tf.math.reciprocal_no_nan(tfmri.estimate_density( samples, shape, method="pipe", max_iter=15 ))

- need to add test

### CODE REVIEW

**Comment by paquiteau** [comment]
Don't worry too much about the density tests, density compensations methods will probably need a new tests setup in the future.

**Comment by chaithyagr** [comment]
This can be merged, @paquiteau ?

**Comment by paquiteau** [comment]
Maybe we should add the same normalization as you did for gpuNUFFT ?

**Comment by chaithyagr** [comment]
I was just going through the codes, we seem to have redundant similar pipe code at: 
https://github.com/mind-inria/mri-nufft/blob/f49c8c001ffff41d24d5267bea9c7f162b669dfb/src/mrinufft/operators/interfaces/tfnufft.py#L139-L157

@Lenoush maybe can you do the same update there also and then make the call to the `pipe` class method? See what is done in `gpuNUFFT` to get clarity.



Also can you please also implement the normalization like it is done at : 
https://github.com/chaithyagr/mri-nufft/blob/45bc400b2cfec8abee4c550780f7a6e5f1fa433c/src/mrinufft/operators/interfaces/gpunufft.py#L512-L517

**Review by paquiteau — CHANGES_REQUESTED** [review]
Almost there ! This keeps getting better.

**Review by chaithyagr — APPROVED** [review]
LGTM, We can merge this right @paquiteau ?

**Review by paquiteau — APPROVED** [review]

**Pull request merged**
