### PR TITLE
Update some examples. 

### PR DESCRIPTION
**Pull request by chaithyagr**
This is fairly straightforward minor changes and should not affect any of the CI

### CODE REVIEW

**Comment by chaithyagr** [comment]
@paquiteau I dont think we need to wait for the tests to complete. Ill let you merge when you think the changes are good. I didnt want to add all these changes as a hotfix, these changes are just based on the issues I saw in docs. We need someway to check if the examples run fine on google-collab or binder, which is missing at the moment.

**Comment by chaithyagr** [comment]
Also, note that examples using utils.py: https://github.com/mind-inria/mri-nufft/blob/fix_examples/examples/utils.py, would not work as the binder / collab instance does not have this file. We need to see how to fix that.. I have documented this in #218

**Comment by paquiteau** [comment]
Do you have any idea on how you would automate the test for google collab ? (If we wish to do so, I am not so sure we should)

Otherwise, LGTM :)

**Comment by chaithyagr** [comment]
> Do you have any idea on how you would automate the test for google collab ? (If we wish to do so, I am not so sure we should)
> 
> Otherwise, LGTM :)

No ideas xD

**Pull request merged**
