### PR TITLE
Direct Torch and CUPY support for gpUNUFFT arrays

### PR DESCRIPTION
**Pull request by chaithyagr**
This PR adds support for direct GPUNUFFT implementations. This prevents copies between CPU and GPU.
Also helps to better add support to torch tensors

### CODE REVIEW

**Comment by chaithyagr** [comment]
Ready for review, all green soon!

**Comment by paquiteau** [comment]
Nicely done ! I think we can use this PR to modify a few things: 

- [ ] Use the `@with_numpy_cupy` decorator also for cufinufft
- [ ] Expose the on-gpu pipe and data consistency method for gpuNUFFT 
- [ ] Add a stacked-gpunufft operator (very similar to stacked-cufinufft) for computing the 2.5D nufft (cufinufft is _very_ fast in 2D, it would be nice to compare between the two)

**Comment by chaithyagr** [comment]
> Nicely done ! I think we can use this PR to modify a few things:
> 
> * [ ]  Use the `@with_numpy_cupy` decorator also for cufinufft
> * [ ]  Expose the on-gpu pipe and data consistency method for gpuNUFFT
> * [ ]  Add a stacked-gpunufft operator (very similar to stacked-cufinufft) for computing the 2.5D nufft (cufinufft is _very_ fast in 2D, it would be nice to compare between the two)

I can handle for 1 and 2 in this PR, 3) to me is a new PR.

**Comment by chaithyagr** [comment]
DOne with both, ill let the tests run first. However, I would want to test both `spectral_radius` estimation and also `pipe` method running ion gpuNUFFT. @paquiteau any tests ? Ideas on where to write them / enable them?

**Comment by paquiteau** [comment]
Spectral Radius (a.k.a Lipschitz Constant) is already tested in `tests/test_interfaces` 
For Pipe density compensation , the easiest might be to compare to a known profile (e.g. 1/r ) for radial

**Pull request merged**
